services:
  jenkins:
    build: .
    image: jenkins/jenkins:jdk21
    user: root
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - demo_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid/config/:/etc/selenoid/:ro
    ports:
      - "4444:4444"
      - "8081:8080"
    restart: unless-stopped

volumes:
  demo_jenkins_home:
    external: true
