services:
  jenkins:
    build: .
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - demo_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  demo_jenkins_home:
    external: true
